# -*- coding: utf-8 -*-
"""Predictive_Analytics_Wine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrYG4FIvEKvIK2sFOTrjx5GfAq5QaESY

# Proyek Predictive Analytics : Wine Quality Dataset
- **Nama:** Atifa Fiorenza
- **Email:** atifafiorenza24@gmail.com
- **ID Dicoding:** atifafiorenza24

## Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
import itertools
import joblib

from imblearn.over_sampling import SMOTE
from scipy.stats.mstats import winsorize
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

"""## Download Dataset"""

from google.colab import files
files.upload()  # Upload file kaggle.json dari lokal

# Membuat folder .kaggle untuk credentials
!mkdir -p ~/.kaggle

# Menyalin file kaggle.json ke folder .kaggle
!cp kaggle.json ~/.kaggle/kaggle.json

# Memberikan permission agar kaggle.json dapat digunakan
!chmod 600 ~/.kaggle/kaggle.json

# Mendownload dataset Rice Leaf Diseases dari Kaggle
!kaggle datasets download -d yasserh/wine-quality-dataset

# Mengekstrak file dataset
!unzip wine-quality-dataset.zip -d wine

"""Load Dataset"""

dataset = 'wine/WineQT.csv'

# Membaca CSV
df = pd.read_csv(dataset)
df.head()

df.shape

"""## Dataset Preprocessing"""

df.info()

"""> Cek null"""

# Menampilkan jumlah missing value per kolom
missing_values = df.isnull().sum()

# Filter hanya kolom dengan missing value > 0
missing_values = missing_values[missing_values > 0]

print(missing_values)

"""> Cek duplicats"""

df[df.duplicated()]

df.describe()

num_cols = df.select_dtypes(include=['int64', 'float64']).columns

print("Numerik :", num_cols)

"""## Distribusi tiap fitur

> Numerik
"""

num_cols1= ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar']
fig, axes = plt.subplots(2, 2, figsize=(18, 10))
axes = axes.flatten()

for i, col in enumerate(num_cols1):
    sns.boxplot(y=df[col], ax=axes[i], color='skyblue')
    axes[i].set_title(f'Boxplot {col}')
    axes[i].set_ylabel(col)

plt.tight_layout()
plt.show()

num_cols2= ['chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',]
fig, axes = plt.subplots(2, 2, figsize=(18, 10))
axes = axes.flatten()

for i, col in enumerate(num_cols2):
    sns.boxplot(y=df[col], ax=axes[i], color='skyblue')
    axes[i].set_title(f'Boxplot {col}')
    axes[i].set_ylabel(col)

plt.tight_layout()
plt.show()

num_cols3= ['pH', 'sulphates', 'alcohol', 'quality']
fig, axes = plt.subplots(2, 2, figsize=(18, 10))
axes = axes.flatten()

for i, col in enumerate(num_cols3):
    sns.boxplot(y=df[col], ax=axes[i], color='skyblue')
    axes[i].set_title(f'Boxplot {col}')
    axes[i].set_ylabel(col)

plt.tight_layout()
plt.show()

# Bikin grid 7x2
fig, axes = plt.subplots(7, 2, figsize=(18, 14))  # ukuran lebih besar
axes = axes.flatten()  # Supaya mudah di-loop

for i, col in enumerate(num_cols):
    sns.histplot(df[col], kde=True, ax=axes[i], color='skyblue')
    axes[i].set_title(f'Distribusi {col}')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Frekuensi')

plt.tight_layout()
plt.show()

"""### Deteksi Perilaku Outliner"""

# Fungsi untuk menghitung dan menampilkan data outlier
def lihat_outlier(kolom_data):
    q1 = kolom_data.quantile(0.25)
    q3 = kolom_data.quantile(0.75)
    iqr = q3 - q1

    batas_bawah = q1 - 1.5 * iqr
    batas_atas = q3 + 1.5 * iqr

    outliers = kolom_data[(kolom_data < batas_bawah) | (kolom_data > batas_atas)]
    return outliers  # kembalikan nilai-nilai outlier, bukan jumlahnya

# Tampilkan outlier untuk kolom 'alcohol'
outlier_values = lihat_outlier(df['residual sugar'])
print("Nilai outlier:", outlier_values)

# Fungsi untuk menghitung dan menampilkan data outlier
def ringkasan_outlier(df, kolom_list):
    summary = []

    for col in kolom_list:
        data = df[col]
        q1 = data.quantile(0.25)
        q3 = data.quantile(0.75)
        iqr = q3 - q1

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        outliers = data[(data < lower) | (data > upper)]
        jumlah = len(outliers)

        if jumlah == 0:
            keterangan = "Tidak ada outlier"
        else:
            # tandai ekstrem jika outlier jauh dari batas normal
            ekstrem = outliers[(outliers < lower*0.5) | (outliers > upper*1.5)]
            keterangan = "Ekstrem" if len(ekstrem) > 0 else "Wajar"

        summary.append({
            "Kolom": col,
            "Jumlah Outlier": jumlah,
            "Min Outlier": outliers.min() if jumlah > 0 else None,
            "Max Outlier": outliers.max() if jumlah > 0 else None,
            "Keterangan": keterangan
        })

    return pd.DataFrame(summary)

# Misal kolom numerik di dataset
numerik_cols = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality']

tabel_outlier = ringkasan_outlier(df, numerik_cols)
print(tabel_outlier)

# Copy df supaya df asli aman
clean_df = df.copy()

# Daftar kolom ekstrem
ekstrem_cols = ['volatile acidity', 'residual sugar', 'chlorides',
                'free sulfur dioxide', 'total sulfur dioxide', 'sulphates']

for col in ekstrem_cols:
    data = clean_df[col]

    # Hitung IQR
    q1 = data.quantile(0.25)
    q3 = data.quantile(0.75)
    iqr = q3 - q1
    upper_limit = q3 + 1.5 * iqr
    lower_limit = q1 - 1.5 * iqr

    # Proporsi outlier
    n = len(data)
    prop_upper = sum(data > upper_limit) / n
    prop_lower = sum(data < lower_limit) / n

    # Simpan di kolom baru *_winsor
    clean_df[col + '_winsor'] = winsorize(data, limits=(prop_lower, prop_upper))

# Hapus kolom ekstrem aslinya
clean_df.drop(columns=ekstrem_cols, inplace=True)

clean_df.head()

"""## Korelasi antar fitur
Gunakan heatmap korelasi untuk melihat hubungan antar variabel

### Sebelum Winsorizing
"""

# Select only numeric columns for correlation
numeric_df = df.select_dtypes(include=['int64', 'float64']).drop(columns=['Id'])

# Compute correlation matrix
corr_matrix = numeric_df.corr()

# Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5, square=True, cbar_kws={"shrink": 0.8})
plt.title("Correlation Matrix of Numeric Features", fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""### Setelah Winsorizing"""

# Select only numeric columns for correlation
numeric_clean_df = clean_df.select_dtypes(include=['int64', 'float64']).drop(columns=['Id'])

# Compute correlation matrix
corr_matrix = numeric_clean_df.corr()

# Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5, square=True, cbar_kws={"shrink": 0.8})
plt.title("Correlation Matrix of Numeric Features", fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""## Perbandingan fitur terhadap target"""

# Daftar fitur numerik yang akan diplot
num_features = ['alcohol', 'volatile acidity_winsor', 'sulphates_winsor', 'citric acid']

# Menyiapkan plot
plt.figure(figsize=(15, 10))

# Membuat subplot untuk setiap fitur
for i, feature in enumerate(num_features):
    plt.subplot(2, 2, i + 1)
    sns.boxplot(x='quality', y=feature, data=clean_df)
    plt.title(f'Distribusi {feature.replace("_", " ").title()} per Quality', fontsize=12)
    plt.xlabel('Quality', fontsize=10)
    plt.ylabel(feature.replace("_", " ").title(), fontsize=10)
    plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

"""## Simpan Clean Data"""

label_df = clean_df.copy()

def quality_group(q):
    if q <= 5:
        return 'low'
    else:
        return 'high'

label_df['quality_label'] = label_df['quality'].apply(quality_group)

label_df['quality_label'].value_counts()

label_df = label_df.drop(['Id','quality','free sulfur dioxide_winsor'], axis=1)
label_df.head()

"""## Pembagian data train"""

numeric_df = label_df.select_dtypes(include=['int64', 'float64']).columns
category_df = label_df.select_dtypes(include=['object']).columns

print(numeric_df.to_list())
print(category_df.to_list())

"""## Encoding"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
label_df['quality_label'] = le.fit_transform(label_df['quality_label'])
label_df.head()

# Misal clean_df masih punya kolom 'quality'
X = label_df.drop('quality_label', axis=1)  # semua kolom kecuali 'quality'
y = label_df['quality_label']               # kolom target

print(y.value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train, y_train)
print(y.value_counts())
print(y_res.value_counts())

"""## Scalling data"""

scaler = RobustScaler()

# Fit scaler hanya di training set
X_train_res_scaled = scaler.fit_transform(X_res)

# Transform test set dengan scaler yang sama
X_test_scaled = scaler.transform(X_test)

"""## Modelling"""

from sklearn.linear_model import LogisticRegression
models = {
    "Logistic Regression" : LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(random_state=42,class_weight='balanced'),
    "XGBoost": XGBClassifier(eval_metric='mlogloss', random_state=42),
    "SVM": SVC(random_state=42),
    "KNN": KNeighborsClassifier(),
}

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

def evaluate_model(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    score = accuracy_score(y_test, y_pred)
    print(f"Score: {score:.4f}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

for name, model in models.items():
    print(f"===== {name} =====")
    if name in ["SVM", "KNN", "Logistic Regression"]:
        evaluate_model(model, X_train_res_scaled, y_res, X_test_scaled, y_test)
    else:
        evaluate_model(model, X_res, y_res, X_test, y_test)
    print("\n")

"""## Hypertuning"""

# Model awal
rf = RandomForestClassifier(random_state=42, class_weight='balanced')

# Range parameter yang mau diuji
param_dist = {
    'n_estimators': randint(100, 500),         # jumlah pohon
    'max_depth': [None, 5, 10, 20, 30],       # kedalaman pohon
    'min_samples_split': randint(2, 10),      # min sampel utk split
    'min_samples_leaf': randint(1, 5),        # min sampel di daun
    'max_features': ['sqrt', 'log2', None]    # fitur maksimum tiap split
}

# Randomized Search
random_search = RandomizedSearchCV(
    rf,
    param_distributions=param_dist,
    n_iter=50,                  # jumlah kombinasi coba
    cv=5,                       # 5-fold cross validation
    scoring='accuracy',         # metrik evaluasi
    random_state=42,
    n_jobs=-1,                  # pakai semua core CPU
    verbose=2
)

# Fit ke data training yang sudah SMOTE + scaling
random_search.fit(X_train_res_scaled, y_res)

# Hasil terbaik
print("Best parameters:", random_search.best_params_)
print("Best CV score:", random_search.best_score_)

# Model terbaik
best_rf = random_search.best_estimator_

y_pred = best_rf.predict(X_test_scaled)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

# Misal rf_model sudah dilatih
joblib.dump(models['Random Forest'], "rf_model.pkl")
print("Model berhasil disimpan ke rf_model.pkl")

"""## Hasil inference/labeling satu data"""

# Misal model sudah dilatih
rf_model = models['Random Forest']
rf_model.fit(X_res, y_res)

# Misal X_test punya kolom yang sama seperti X_res
single_sample = X_test.iloc[0]  # ambil baris pertama
single_sample_df = pd.DataFrame([single_sample], columns=X_res.columns)

# Prediksi
pred_class = rf_model.predict(single_sample_df)[0]
pred_prob = rf_model.predict_proba(single_sample_df)[0]

print(f"Predicted class: {pred_class}")
print(f"Predicted probability: {pred_prob}")