# -*- coding: utf-8 -*-
"""Predictive_Analytics_Wine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrYG4FIvEKvIK2sFOTrjx5GfAq5QaESY

# Proyek Predictive Analytics : Wine Quality Dataset
- **Nama:** Atifa Fiorenza
- **Email:** atifafiorenza24@gmail.com
- **ID Dicoding:** atifafiorenza24

## Import Library
We need to import some library that will be used in data preprocessing, data manipulation, and modeling.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
import itertools
import joblib

from scipy.stats.mstats import winsorize
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV
from scipy.stats import randint
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

"""## Download Dataset
Download the wine dataset. The dataset is from UCI Machine Learning and can be downloaded at Kaggle

https://www.kaggle.com/datasets/yasserh/wine-quality-dataset
"""

from google.colab import files
files.upload()  # Upload file kaggle.json dari lokal

# Membuat folder .kaggle untuk credentials
!mkdir -p ~/.kaggle

# Menyalin file kaggle.json ke folder .kaggle
!cp kaggle.json ~/.kaggle/kaggle.json

# Memberikan permission agar kaggle.json dapat digunakan
!chmod 600 ~/.kaggle/kaggle.json

# Mendownload dataset Rice Leaf Diseases dari Kaggle
!kaggle datasets download -d yasserh/wine-quality-dataset

# Mengekstrak file dataset
!unzip wine-quality-dataset.zip -d wine

"""## Load Dataset
Load and read wine dataset from folder wine
"""

dataset = 'wine/WineQT.csv'

# Membaca CSV
df = pd.read_csv(dataset)
df.head()

"""## Data Understanding
First we want to find basic information from the dataset, like shape, data type, general stats, null values, and duplicate data. Than we will doing some EDA.
"""

df.shape

df.info()

df.describe()

df.isna().sum()

df.duplicated().sum()

num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

"""## Data Visualization & EDA
uses univariate and multivariate visualizations to understand data distribution, detect outliers, and reveal relationships between features before modeling.

### Univariate Analysis
Univariate analysis is focusing on one variable at a time. The main goal is to describe, summarize, and find patterns in the data. At this stage, the data will be shown using a **histogram** to visualize the distribution and a **boxplot** to identify potential outliers and understand the spread of the data.
"""

fig, axes = plt.subplots(7, 2, figsize=(18, 14))  # ukuran lebih besar
axes = axes.flatten()  # Supaya mudah di-loop

for i, col in enumerate(num_cols):
    sns.histplot(df[col], kde=True, ax=axes[i], color='skyblue')
    axes[i].set_title(f'Distribution of {col}')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Count')

# Hapus subplot yang tidak terpakai
for j in range(len(num_cols), len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.savefig('univariate_histogram.png', dpi=300, bbox_inches='tight')
plt.show()

"""Berdasarkan hasil histogram diatas :
- Banyak fitur miring ke kanan (skewed): Fitur seperti **residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, dan alcoho**l memiliki ekor panjang ke kanan. Ini menunjukkan **ada beberapa nilai yang sangat tinggi (outlier)**. Dalam plot KDE, kurvanya akan terlihat memanjang ke kanan.
- Beberapa fitur normal: Fitur volatile acidity, density, dan pH memiliki sebaran yang lebih simetris, mirip kurva lonceng. Plot KDE untuk fitur ini akan menyerupai bentuk lonceng.
- Fitur kategorikal: Fitur quality memiliki nilai yang terpusat di 5, 6, dan 7. Untuk fitur seperti ini, histogram lebih cocok daripada KDE.
- Identitas unik: Fitur Id bukan data yang berguna untuk analisis karena setiap nilainya unik.
"""

# Tentukan layout grid otomatis
n_cols = 3  # jumlah plot per baris
n_rows = math.ceil(len(num_cols) / n_cols)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(6*n_cols, 5*n_rows))
axes = axes.flatten()  # flatten supaya mudah di-loop

for i, col in enumerate(num_cols):
    sns.boxplot(y=df[col], ax=axes[i], color='skyblue')
    axes[i].set_title(f'Boxplot {col}')
    axes[i].set_ylabel(col)

# Hapus subplot kosong jika ada
for j in range(len(num_cols), len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.savefig('univariate_boxplot.png', dpi=300, bbox_inches='tight')
plt.show()

"""Dari hasil boxplot, seluruh fitur memiliki outlier yang terlihat dari titik-titik di luar whisker. Beberapa fitur seperti **residual sugar, chlorides, free sulfur dioxide, dan total sulfur dioxide** memiliki jumlah outlier yang banyak, sedangkan fitur seperti **alcohol, sulphates, fixed acidity, volatile acidity, density, serta citric acid, pH, dan quality** memiliki outlier lebih sedikit. Hal ini perlu dipertimbangkan saat preprocessing untuk mengurangi dampak negatif outlier terhadap model.

### Multivariate Analysis
Multivariate analysis examines the relationships between three or more variables simultaneously. At this stage, the data will be shown using a **heatmap** to visualize the correlation matrix and a **scatterplot** to show the distribution of multiple features with respect to the target variable quality.
"""

# Select only numeric columns for correlation
numeric_df = df.select_dtypes(include=['int64', 'float64']).drop(columns=['Id'])

# Compute correlation matrix
corr_matrix = numeric_df.corr()

# Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5, square=True, cbar_kws={"shrink": 0.8})
plt.title("Correlation Matrix of Numeric Features", fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig('multivariate_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

"""Dari hasil heatmap diatas ditemukan ada beberapa fitur yang memiliki korelasi yang cukup tinggi > 0.60 :
1. fixed acidity ↔ citric acid → **0.67**
2. fixed acidity ↔ density → **0.68**
3. free sulfur dioxide ↔ total sulfur dioxide → **0.66**

Cek korelasi ke target (quality) dan lihat fitur mana di setiap pasangan yang punya korelasi absolut lebih besar dengan target → itu yang dipertahankan.

1. fixed acidity → 0.12
2. citric acid → 0.24 ✅ (lebih kuat ke target)
density → -0.18
4. free sulfur dioxide → -0.06
5. total sulfur dioxide → -0.18 ✅ (lebih kuat ke target, walau negatif)

**Rekomendasi awal (berdasarkan korelasi ke target saja)**

**fixed acidity ↔ citric acid** →
- Dari segi ilmu oenologi (ilmu wine), citric acid
sering lebih berpengaruh ke kualitas persepsi rasa karena memberi freshness dan aroma citrus yang positif.
- Fixed acidity memang penting, tapi terlalu tinggi bisa membuat wine terlalu asam dan tidak enak.
- Korelasi ke quality (data kamu sebelum winsor): citric acid (0.24) > fixed acidity (0.12).
- **Rekomendasi: Pilih citric acid.**


**fixed acidity ↔ density** →
- Density banyak dipengaruhi gula & alkohol.
- Dalam penilaian kualitas, alkohol dan gula berperan besar pada body dan balance, jadi density bisa jadi indikator yang baik.
- Korelasi ke quality: density (-0.18) sedikit lebih besar absolutnya daripada fixed acidity (0.12), tapi negatif → artinya density tinggi sering muncul di wine yang kualitasnya lebih rendah (misalnya wine manis dengan gula sisa tinggi).
- **Rekomendasi: Pilih density**

**free sulfur dioxide ↔ total sulfur dioxide** →
- SO₂ memengaruhi stabilitas dan umur simpan, tapi kadar yang terlalu tinggi bisa merusak aroma & rasa.
- Free SO₂ lebih berpengaruh langsung terhadap rasa dan aroma saat ini dibanding total SO₂.
- Korelasi ke quality: total SO₂ (-0.18) > free SO₂ (-0.06) secara absolut, tapi arah negatif menunjukkan kadar tinggi sering menurunkan kualitas.
- **Rekomendasi: Pilih total sulfur dioxide**
"""

# Asumsi target = 'quality'
target = 'quality'

# Buat figure grid
num_cols = numeric_df.columns.drop(target)  # semua kolom numeric kecuali target
n_cols = 3  # jumlah kolom per row
n_rows = (len(num_cols) + n_cols - 1) // n_cols

fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols*5, n_rows*4))
axes = axes.flatten()

for i, col in enumerate(num_cols):
    sns.scatterplot(x=numeric_df[target], y=numeric_df[col], ax=axes[i], color='skyblue')
    axes[i].set_title(f'{col} vs {target}')
    axes[i].set_xlabel(target)
    axes[i].set_ylabel(col)

# Hapus axes yang kosong kalau ada
for j in range(i+1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.savefig('multivariate_scatterplot.png', dpi=300, bbox_inches='tight')
plt.show()

"""Berdasarkan grafik scatter plot yang Anda berikan, berikut adalah pola yang terlihat dari hubungan antara setiap fitur dengan quality:

**Hubungan Positif (Semakin tinggi fitur, semakin tinggi quality)**
- **alcohol vs quality**:  Terlihat tren positif yang cukup jelas. Titik-titik data cenderung naik ke kanan, menunjukkan bahwa anggur dengan kadar alcohol yang lebih tinggi cenderung memiliki nilai quality yang lebih tinggi.

- **citric acid vs quality**:  Ada tren positif, meski tidak sekuat alcohol. Ketika kadar citric acid meningkat, quality juga cenderung meningkat, menunjukkan kontribusi positif terhadap rasa.

- **sulphates vs quality**:  Terlihat adanya tren positif. Peningkatan kadar sulphates seringkali berhubungan dengan nilai quality yang lebih tinggi.

**Hubungan Negatif (Semakin tinggi fitur, semakin rendah quality)**
- **volatile acidity vs quality**: Terdapat tren negatif yang cukup jelas. Semakin tinggi volatile acidity, semakin rendah nilai quality anggur. Ini menunjukkan bahwa keasaman yang mudah menguap tinggi tidak diinginkan untuk kualitas anggur yang baik.
- **density vs quality**:  Ada tren negatif, meskipun hubungannya tidak terlalu kuat. Peningkatan density cenderung berhubungan dengan sedikit penurunan quality.

**Hubungan Tidak Jelas (Korelasi lemah)**
- Untuk fitur-fitur seperti fixed acidity, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, dan pH, sebaran titik-titik datanya tampak acak dan tidak membentuk pola yang jelas. Ini menunjukkan bahwa korelasi antara fitur-fitur ini dengan quality sangat lemah atau hampir tidak ada.

## Dataset Preprocessing
After doing some analysis, we will do data preparation like removing null values, duplicates, and outliers. We also will normalize the feature to make them have equall weights for the ML models.
"""

clean_df = df.copy()

# Menghitung jumlah nilai kosong di setiap kolom
missing_values = clean_df.isna().sum()
print(missing_values[missing_values > 0])

clean_df = clean_df.drop_duplicates()
clean_df.duplicated().sum()

"""After cleaning data, we will removing outlier from some of the important features. This is because outliers can make bias for the model. We use **winsorize** to reduce the influence of extreme values and optimize the model's performance."""

# Fungsi untuk menghitung dan menampilkan data outlier
def ringkasan_outlier(df, kolom_list):
    summary = []

    for col in kolom_list:
        data = df[col]
        q1 = data.quantile(0.25)
        q3 = data.quantile(0.75)
        iqr = q3 - q1

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        outliers = data[(data < lower) | (data > upper)]
        jumlah = len(outliers)

        if jumlah == 0:
            keterangan = "Tidak ada outlier"
        else:
            # tandai ekstrem jika outlier jauh dari batas normal
            ekstrem = outliers[(outliers < lower*0.5) | (outliers > upper*1.5)]
            keterangan = "Ekstrem" if len(ekstrem) > 0 else "Wajar"

        summary.append({
            "Kolom": col,
            "Jumlah Outlier": jumlah,
            "Min Outlier": outliers.min() if jumlah > 0 else None,
            "Max Outlier": outliers.max() if jumlah > 0 else None,
            "Keterangan": keterangan
        })

    return pd.DataFrame(summary)

# Misal kolom numerik di dataset
numeric_df = clean_df.select_dtypes(include=['int64', 'float64']).drop(columns=['Id'])

tabel_outlier = ringkasan_outlier(clean_df, numeric_df)
print(tabel_outlier)

"""As you can see, the outliers in the extreme category are volatile acidity, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, and sulphates. We need to treat these outliers using winsorization."""

# Daftar kolom ekstrem
ekstrem_cols = ['volatile acidity', 'residual sugar', 'chlorides',
                'free sulfur dioxide', 'total sulfur dioxide', 'sulphates']

for col in ekstrem_cols:
    data = clean_df[col]

    # Hitung IQR
    q1 = data.quantile(0.25)
    q3 = data.quantile(0.75)
    iqr = q3 - q1
    upper_limit = q3 + 1.5 * iqr
    lower_limit = q1 - 1.5 * iqr

    # Proporsi outlier
    n = len(data)
    prop_upper = sum(data > upper_limit) / n
    prop_lower = sum(data < lower_limit) / n

    # Simpan kembali ke kolom aslinya
    clean_df[col] = winsorize(data, limits=(prop_lower, prop_upper))

clean_df.shape

"""Next, we also need to convert the target values from 10 categories into 3 categories, because we want to classify whether the wine is having a low , medium, or high qualty"""

clean_df['quality'].value_counts()

clean_df["quality"] = pd.cut(clean_df["quality"], bins=[0, 4, 6, 10], labels=["low", "medium", "high"])

clean_df['quality'].value_counts()

# encode the target values, use 0 for bad, 1 for medium, and 2 for good
clean_df["quality"] = clean_df["quality"].map({"low": 0, "medium": 1,"high":2})

clean_df.head()

"""Drop Column Id because it can't use for modelling"""

# Drop kolom 'id' dari dataframe
clean_df = clean_df.drop('Id', axis=1)

# Cek hasilnya
clean_df.head()

"""The features are already cleaned, now we need to split for training and testing. Then we need transform it using robust scaler to make the data have equal weight, so it can increase the performance and reduce the bias of the ML models."""

# Misal clean_df masih punya kolom 'quality'
X = clean_df.drop(['quality'], axis=1)
y = clean_df['quality']

print(X.columns)
print(y.value_counts())

"""Split data into 80 train 20 test"""

# Split data into 80/20
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""Apply SMOTE on the training set only to address class imbalance in the target variable"""

# SMOTE hanya di training set
smote = SMOTE(random_state=42)
X_resample, y_resample = smote.fit_resample(X_train, y_train)
print("Distribusi asli:")
print(y.value_counts())
print("\nDistribusi setelah SMOTE:")
print(y_resample.value_counts())

"""Scale features using RobustScaler to reduce the impact of outliers"""

# Scaling
scaler = RobustScaler()
X_train_scaled = scaler.fit_transform(X_resample)
X_test_scaled = scaler.transform(X_test)

"""## Modelling
Because the data processing is already done, next we will train a model to do the classification. We will use 4 models, KNN, SVM, XGBoost and Random Forest. Those model are choosen because it some of the most common model used for classification.
"""

# Model
models = {
    "Random Forest": RandomForestClassifier(random_state=42, n_estimators=100),
    "XGBoost": XGBClassifier(eval_metric='mlogloss', random_state=42),
    "SVM": SVC(C=1.0, kernel="rbf", gamma="scale"),
    "KNN": KNeighborsClassifier(n_neighbors=5)
}

label_map = {0: 'Low', 1: 'Medium', 2: 'High'}
accuracy_scores = {}

# Fungsi evaluasi
def evaluate_model(model, name, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    score = accuracy_score(y_test, y_pred)
    accuracy_scores[name] = score
    print(f"Score: {score:.4f}")
    print(classification_report(y_test, y_pred,target_names=label_map.values()))
    print(confusion_matrix(y_test, y_pred))

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.title('Confusion Matrix')
    plt.show()

# Loop evaluasi
for name, model in models.items():
    print(f"===== {name} =====")
    evaluate_model(model, name, X_train_scaled, y_resample, X_test_scaled, y_test)
    print("\n")

"""## Evaluation"""

# Data
models_names = list(accuracy_scores.keys())
accuracy_percent = [v * 100 for v in accuracy_scores.values()]

# Custom colors: dark purple, dark blue, green, yellow
custom_colors = ['#1A2A80', '#3B38A0', '#7A85C1', '#B2B0E8']

plt.figure(figsize=(10, 6))
bars = plt.bar(models_names, accuracy_percent, color=custom_colors[:len(models_names)])

plt.title('Comparison of Classification Model Accuracy')
plt.xlabel('Model')
plt.ylabel('Accuracy Score (%)')
plt.ylim(min(accuracy_percent) - 5, 90)

# Menambahkan teks persen di atas batang
for bar, score in zip(bars, accuracy_percent):
    plt.text(bar.get_x() + bar.get_width()/2, score + 1, f'{score:.2f}%', ha='center', va='bottom')

# Simpan gambar
plt.savefig('model_accuracy_comparison.png', dpi=300, bbox_inches='tight')  # simpan sebagai PNG
plt.show()

"""Based on the model evaluation table, the **Random Forest model** is the best performer with the highest accuracy of **0.85**. It's the most balanced model, although all models—including Random Forest and XGBoost struggle significantly with predicting class 0. This is evident from the very low precision, recall, and f1-scores for that class. The **SVM and KNN models are the weakest**, with lower overall accuracy, and they also struggle with predictions, especially for classes 0 and 1. To improve the overall performance, it's crucial to address the poor prediction of class 0, possibly due to data imbalance.

We will save the model using joblib
"""

# Misal rf_model sudah dilatih
joblib.dump(models['Random Forest'], "rf_model.pkl")
print("Model berhasil disimpan ke rf_model.pkl")

"""## Inference on a Single Test
To perform inference or labeling on a single piece of data, we use a trained model to make a prediction on a new, unseen data point. This process involves selecting one example from the test set, ensuring it is in the correct format, and then passing it to the model's .predict() method
"""

print("--- Performing inference from the saved model ---")

# 1. Load the best model from the .pkl file
best_model = joblib.load("rf_model.pkl")

# 2. Select a single data example from the scaled test set
# We will use the first row of the test data as our example
single_test_example = X_test_scaled[100]

# 3. Reshape the data for the model
# The .predict() method expects a 2D array, so we reshape the single row
single_test_example = single_test_example.reshape(1, -1)

# 4. Make a prediction (labeling)
prediction_numeric = best_model.predict(single_test_example)

# 5. Get the actual label for comparison
actual_label_numeric = y_test.iloc[0]

# 6. Convert numeric labels to their descriptive names
prediction_label = label_map[prediction_numeric[0]]
actual_label = label_map[actual_label_numeric]

# 7. Print the results
print(f"The model predicted the label as: {prediction_label}")
print(f"The actual label for this data point is: {actual_label}")